name: kigali_bus_tracker
description: A new Flutter project to track buses and traffic in Kigali, Rwanda.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.0
  location: ^4.3.0
  http: ^0.14.0
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
